services:
  mariadb:
    image: mariadb:lts
    container_name: mariadb-tam
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ${DB_LOC}:/var/lib/mysql:Z
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
  tam:
    image: dbob16/tam-server
    container_name: tam1
    depends_on:
      mariadb:
        condition: service_started
        restart: true
    environment:
      API_PW: ${API_PW}
      SS_MODE: ${SS_MODE}
      DB_TYPE: MYSQL
      MARIADB_HOST: mariadb
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - '127.0.0.1:8000:80'
    healthcheck:
      test: curl --fail http://localhost:80/health/ || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: always

# Enable ssl by uncommenting these following lines and putting nginx.crt (server certificate) and nginx.key (server key) in certs
  # nginx:
  #   image: nginx
  #   container_name: nginx-tam-rp
  #   depends_on:
  #     mariadb:
  #       condition: service_started
  #       restart: true
  #     tam:
  #       condition: service_started
  #       restart: true
  #   network_mode: host
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./certs:/etc/nginx/certs:ro
  #   healthcheck:
  #     test: ["CMD", "service", "nginx", "status"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 5s
  #   restart: always

# Enable restarting of unhealthy services by uncommenting the following lines:
  # autoheal:
  #   restart: always
  #   image: willfarrell/autoheal
  #   container_name: autoheal
  #   environment:
  #     - AUTOHEAL_CONTAINER_LABEL=all
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock